name: Checks

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    env:
      # 透過 Repository → Settings → Variables 設置，true 代表跳過 Tauri 測試
      SKIP_TAURI_TESTS: ${{ vars.SKIP_TAURI_TESTS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Format check
        run: npm run format:check

      - name: Type check (build config)
        run: npm run type-check:build

      - name: Build (vite)
        run: npm run build

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Tests (web)
        run: npm run test

      - name: Tests (tauri)
        if: env.SKIP_TAURI_TESTS != 'true'
        run: npm run test:tauri
